# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BulkRename < Formula
  desc "Easy files renaming tools which rename files in a bulk manner."
  homepage "https://github.com/seehait-c/bulk-rename"
  version "0.0.2"
  license "MIT"

  on_macos do
    url "https://github.com/seehait-c/bulk-rename/releases/download/0.0.2/bulk-rename_0.0.2_Darwin_all.tar.gz"
    sha256 "c9d040a92f81cd85a2906a8def78ef9d2a14b4c20a300744a9af8914cb719672"

    def install
      bin.install "bulk-rename"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/seehait-c/bulk-rename/releases/download/0.0.2/bulk-rename_0.0.2_Linux_x86_64.tar.gz"
      sha256 "11cc54d02c68385bbe722fa9ead0a6bf5c9edbc9a2be7d7c419fc6c1a710d8a4"

      def install
        bin.install "bulk-rename"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seehait-c/bulk-rename/releases/download/0.0.2/bulk-rename_0.0.2_Linux_arm64.tar.gz"
      sha256 "805fbabc36113ba7de85a615cf9e861f13860ac43155e08aad4a5641f772fce6"

      def install
        bin.install "bulk-rename"
      end
    end
  end
end
