# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BulkRename < Formula
  desc "Easy files renaming tools which rename files in a bulk manner."
  homepage "https://github.com/seehait-c/bulk-rename"
  version "0.0.4"
  license "MIT"

  on_macos do
    url "https://github.com/seehait-c/bulk-rename/releases/download/0.0.4/bulk-rename_0.0.4_Darwin_all.tar.gz"
    sha256 "1a643fc14fe3d19da9b79de774a4f29cb34a92c43dfc40cf0cd91897d11a9b6a"

    def install
      bin.install "bulk-rename"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/seehait-c/bulk-rename/releases/download/0.0.4/bulk-rename_0.0.4_Linux_x86_64.tar.gz"
      sha256 "954e394992e748bce88683f5476c905c5172174666195a66cec6edd2bbe1fe42"

      def install
        bin.install "bulk-rename"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seehait-c/bulk-rename/releases/download/0.0.4/bulk-rename_0.0.4_Linux_arm64.tar.gz"
      sha256 "6f88961fe7e76db2948dea9ef26e3e5f173969309032d4c183c62d73443bcf15"

      def install
        bin.install "bulk-rename"
      end
    end
  end
end
